### ISSUE TITLE
Hadoop dependencies should be marked as provided

### ISSUE THREAD

**Issue by superdude264** [diana-hep/root4j#2]
https://github.com/diana-hep/root4j/blob/master/pom.xml#L69

By not providing a scope, the dependencies are set to the compile scope by default.  This means anyone that includes root4j in their project (directly or not) is going to get hadoop-client 2.7.3 & hadoop-hdfs 2.7.3 and all their transitive dependencies.  For infrastructure libraries (like), this is not normally the intention, as most runtime environment will provide such JARs.  See Maven docs for more info: https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Scope

**Comment by vkhristenko** [comment]
Spark will pull the right version of hadoop libs
Discussed with Rob - will incorporate soon!

VK

**Comment by vkhristenko** [comment]
should be fixed as of 2a7bd47582755a5bc85dd8b05ed5ee7d9fecf6f6 commit
version 0.1.6.

@superdude264 let me know if it's still not working
